---
title: "Observation Frequency Visualization"
author: "Bennett McAfee"
date: "2023-09-22"
output: html_document
---

```{r}
library(tidyverse)
library(arrow)

data <- open_dataset("D:\\bensd\\Documents\\RStudio Workspace\\Eco-KGML\\DataCleaning_Scripts\\data")

data$schema[[7]] <- Field$create("flag1", string())

head(data)

mendota <- data %>% filter(lake == "Mendota") %>% collect()
```

```{r}
var = c()
dep = c()
modediff = c()

for (x in unique(mendota$variable)){
  sub <- mendota %>% subset(variable == x)
  sub <- sub[order(sub$datetime),]
  for (y in unique(sub$depth)){
    sub2 <- sub %>% subset(depth == y)
    mem <- c()
    for (i in 2:nrow(sub2)){
      diff <- difftime(sub2$datetime[i], sub2$datetime[i-1], units = "days")
      mem[i-1] <- diff
    }
    var <- append(var, x)
    dep <- append(dep, y)
    modediff <- append(modediff, median(mem, na.rm = TRUE))
  }
}

obs <- data.frame("Variable" = var, "Depth" = dep, "Frequency" = modediff)

obs_wide <- pivot_wider(obs, names_from = Variable, values_from = Frequency)
obs_wide <- obs_wide[order(obs_wide$Depth),]
write.csv(obs_wide, "observation_frequency.csv", row.names = FALSE)

```
